pipeline {
    agent any 
    tools {
        // Note: this should match with the tool name configured in your jenkins instance (JENKINS_URL/configureTools/)
        maven "MVN_HOME"
        
    }
	 environment {
        // This can be nexus3 or nexus2
        NEXUS_VERSION = "nexus3"
        // This can be http or https
        NEXUS_PROTOCOL = "http"
        // Where your Nexus is running
        NEXUS_URL = "54.86.237.152:8081"
        // Repository where we will upload the artifact
        NEXUS_REPOSITORY = "devops"
        // Jenkins credential id to authenticate to Nexus OSS
        NEXUS_CREDENTIAL_ID = "Nexus_server"
    }
    stages {
        stage("clone code") {
            steps {
                script {
                    // Let's clone the source
                    git 'https://github.com/Mahesh713-MB/spring3-mvc-maven-xml-hello-world-1.git';
                }
            }
        }
        stage("mvn build") {
            steps {
                script {
                    // If you are using Windows then you should use "bat" step
                    // Since unit testing is out of the scope we skip them
                    sh 'mvn -Dmaven.test.failure.ignore=true install'
                }
            }
        }
		stage('Verify Artifact') {
    steps {
        sh '''
            test -f target/ncodeit-hello-world-3.0.war
            ls -lh target/ncodeit-hello-world-3.0.war
        '''
        archiveArtifacts artifacts: 'target/ncodeit-hello-world-3.0.war',
                         fingerprint: true
    }
}
stage('publish to nexus') {
    steps {
        script {
            // Read Maven project information
            def pom = readMavenPom file: 'pom.xml'

            // Find the artifact generated by Maven
            def filesByGlob = findFiles(
                glob: "target/*.${pom.packaging}"
            )

            // Verify that an artifact was found
            if (filesByGlob.length == 0) {
                error "No ${pom.packaging} artifact found in target directory"
            }

            // Select the generated artifact
            def artifactPath = filesByGlob[0].path

            // Verify that the artifact exists
            if (!fileExists(artifactPath)) {
                error "Artifact not found: ${artifactPath}"
            }

            // Print artifact information
            echo "Artifact name: ${filesByGlob[0].name}"
            echo "Artifact path: ${artifactPath}"
            echo "Artifact size: ${filesByGlob[0].length} bytes"
            echo "Group ID: ${pom.groupId}"
            echo "Artifact ID: ${pom.artifactId}"
            echo "Packaging: ${pom.packaging}"

            // Upload artifact and POM to Nexus
            nexusArtifactUploader(
                nexusVersion: NEXUS_VERSION,
                protocol: NEXUS_PROTOCOL,
                nexusUrl: NEXUS_URL,
                groupId: pom.groupId,
                artifactId: pom.artifactId,
                version: "${BUILD_NUMBER}",
                repository: NEXUS_REPOSITORY,
                credentialsId: NEXUS_CREDENTIAL_ID,
                artifacts: [
                    [
                        artifactId: pom.artifactId,
                        classifier: '',
                        file: artifactPath,
                        type: pom.packaging
                    ],
                    [
                        artifactId: pom.artifactId,
                        classifier: '',
                        file: 'pom.xml',
                        type: 'pom'
                    ]
                ]
            )

            echo 'Artifact upload to Nexus completed.'
        }
    }
}
